### ISSUE TITLE
GNOME 3.22

### ISSUE THREAD

**Issue by jonrouleau** [jrouleau/gnome-shell-extension-gravatar#5]
Created a branch for GNOME 3.22, however, I do not currently have a machine to test on.

Any feedback here would be greatly appreciated!

**Comment by redianthus** [comment]
I didn't try your new branch, but the version from gnome shell extension website works great on 3.22 (Debian Unstable). As your 3.22 branch doesn't seem to change anything in the code, I think it would also work well. ;)
