### ISSUE TITLE
No longer seems to work in GNOME 3.32

### ISSUE THREAD

**Issue by sardaukar** [jrouleau/gnome-shell-extension-gravatar#8]

**Comment by sardaukar** [comment]
![Untitled](https://user-images.githubusercontent.com/153407/55282124-de551200-5335-11e9-96c6-393dd8cc90ef.png)

**Comment by sardaukar** [comment]
In "Settings" my avatar is properly set, but not in the menu here - I'm using Manjaro Linux.

**Comment by jonrouleau** [comment]
Okay. I don't actively use GNOME anymore, but I'll try to run some tests on it this week

**Comment by jonrouleau** [comment]
GNOME 3.32 does not seem to show the user's image in that menu anymore. Disabling this extension and setting the image manually does not change the icon there either. Thus, this is not an issue with this extension.
